# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.4
  - hhvm


matrix:
  include:
    - php: 5.5
      env: WP_TRAVISCI=travis:js
    - php: 5.2
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.3
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.4
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.5
      env: WP_TRAVISCI=travis:phpunit
    - php: 5.6
      env: WP_TRAVISCI=travis:phpunit
    - php: hhvm
      env: WP_TRAVISCI=travis:phpunit
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

env:
  - WP_VERSION=master WP_MULTISITE=1



# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --coverage-text


